title: Minqi Mao

# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.


# Define post url by yourself
permalink: /blog/:title.html
timezone: Asia/Chongqing

# Overriden by GitHub Pages: https://help.github.com/articles/using-jekyll-with-pages#configuring-jekyll
safe: true
lsi: false
# markdown: kramdown
# kramdown:
  # input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
    # extensions:
    # - autolink
    # - footnotes
    # - smart
  # use_coderay: true
  # syntax_highlighter: rouge
  # coderay:
    # coderay_line_numbers:  nil

# Origin --- Mao	
#markdown: redcarpet
#redcarpet:
   #extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "strikethrough", "underline"]


markdown: kramdown
kramdown:
   extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "strikethrough", "underline"]

   
# Keybase
include:
  - .well-known

# White-listed plugins
gems:
  - jekyll-sitemap
